config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'pages/index'
  get 'pages/about'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :account_executives
  resources :salespeople
  resources :salepeople
  resources :engineers
  resources :sales_stages
  resources :products
  resources :opportunities do
    resources :comments
    resources :support_opportunities
    #get 'search', to: 'opportunities#search', as: 'search', on: :collection
    get 'search', to: 'opportunities#search', on: :collection
  end
  get 'my-top-opps', to: 'opportunities#tracking', as: 'tracking'
  get 'ac-opps', to: 'support_opportunities#acopps', as: 'acopps'
  resources :support_opportunities do
    resources :opportunities
    resources :apple_cares
  end
  resources :apple_cares

  root to: "opportunities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account_executive.rb
class AccountExecutive < ApplicationRecord
  has_many :opportunities
  #scope :account_executive_fullname, -> { firstname + lastname }

  def account_executive_fullname
  	firstname + " " + lastname
  end



end

app/controllers/account_executives_controller.rb
class AccountExecutivesController < ApplicationController
  before_action :set_account_executive, only: [:show, :edit, :update, :destroy]

  # GET /account_executives
  # GET /account_executives.json
  def index
    @account_executives = AccountExecutive.all
  end

  # GET /account_executives/1
  # GET /account_executives/1.json
  def show
  end

  # GET /account_executives/new
  def new
    @account_executive = AccountExecutive.new
  end

  # GET /account_executives/1/edit
  def edit
  end

  # POST /account_executives
  # POST /account_executives.json
  def create
    @account_executive = AccountExecutive.new(account_executive_params)

    respond_to do |format|
      if @account_executive.save
        format.html { redirect_to @account_executive, notice: 'Account executive was successfully created.' }
        format.json { render :show, status: :created, location: @account_executive }
      else
        format.html { render :new }
        format.json { render json: @account_executive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_executives/1
  # PATCH/PUT /account_executives/1.json
  def update
    respond_to do |format|
      if @account_executive.update(account_executive_params)
        format.html { redirect_to @account_executive, notice: 'Account executive was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_executive }
      else
        format.html { render :edit }
        format.json { render json: @account_executive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_executives/1
  # DELETE /account_executives/1.json
  def destroy
    @account_executive.destroy
    respond_to do |format|
      format.html { redirect_to account_executives_url, notice: 'Account executive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_executive
      @account_executive = AccountExecutive.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_executive_params
      params.require(:account_executive).permit(:firstname, :lastname, :carrier)
    end
end

app/helpers/account_executives_helper.rb
module AccountExecutivesHelper
end

app/views/account_executives/_form.html.erb
<%= form_with(model: account_executive, local: true) do |form| %>
  <% if account_executive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_executive.errors.count, "error") %> prohibited this account_executive from being saved:</h2>

      <ul>
      <% account_executive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :carrier %>
    <%= form.text_field :carrier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/account_executives/edit.html.erb
<h1>Editing Account Executive</h1>

<%= render 'form', account_executive: @account_executive %>

<%= link_to 'Show', @account_executive %> |
<%= link_to 'Back', account_executives_path %>

app/views/account_executives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Executives</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Carrier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_executives.each do |account_executive| %>
      <tr>
        <td><%= account_executive.firstname %></td>
        <td><%= account_executive.lastname %></td>
        <td><%= account_executive.carrier %></td>
        <td><%= link_to 'Show', account_executive %></td>
        <td><%= link_to 'Edit', edit_account_executive_path(account_executive) %></td>
        <td><%= link_to 'Destroy', account_executive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account Executive', new_account_executive_path %>

app/views/account_executives/new.html.erb
<h1>New Account Executive</h1>

<%= render 'form', account_executive: @account_executive %>

<%= link_to 'Back', account_executives_path %>

app/views/account_executives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @account_executive.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @account_executive.lastname %>
</p>

<p>
  <strong>Carrier:</strong>
  <%= @account_executive.carrier %>
</p>

<%= link_to 'Edit', edit_account_executive_path(@account_executive) %> |
<%= link_to 'Back', account_executives_path %>