config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'pages/index'
  get 'pages/about'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :account_executives
  resources :salespeople
  resources :salepeople
  resources :engineers
  resources :sales_stages
  resources :products
  resources :opportunities do
    resources :comments
    resources :support_opportunities
    #get 'search', to: 'opportunities#search', as: 'search', on: :collection
    get 'search', to: 'opportunities#search', on: :collection
  end
  get 'my-top-opps', to: 'opportunities#tracking', as: 'tracking'
  get 'ac-opps', to: 'support_opportunities#acopps', as: 'acopps'
  resources :support_opportunities do
    resources :opportunities
    resources :apple_cares
  end
  resources :apple_cares

  root to: "opportunities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :opportunity, optional: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # The order of these before actions is vital to functionality
  before_action :get_opportunity
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    #@comments = Comment.all
    @comments = @opportunity.comments.order(created_at: :asc)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    #@comment = Comment.new
    @comment = @opportunity.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # @comment = Comment.new(comment_params)
    @comment = @opportunity.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.js

        #format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        #format.html { redirect_to opportunity_comments_path(@opportunity), notice: 'Comment was successfully created.' }
        #format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        #format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.html { redirect_to opportunity_comment_path(@opportunity), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      #format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.html { redirect_to opportunity_comments_path(@opportunity), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_opportunity
      @opportunity = Opportunity.find(params[:opportunity_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    #def set_comment
      #@comment = Comment.find(params[:id])
      #@comment = @opportunity.comments.find(params[:id])
    #end
    def set_comment
      #@comment = Comment.find(params[:id])
      @comment = @opportunity.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:author, :content, :opportunity_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@opportunity, comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area(:content, cols: 50, rows: 2) %>
  </div>
  
  <div class="field">
    <%= form.label 'Author:' %> <%= current_user.fullname %>
    <%= form.hidden_field :author, value: current_user.fullname %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_new_comment.html.erb
<%= form_with(model: [@opportunity, Comment.new] ) do |form| %>
      <%= form.hidden_field :author, value: current_user.fullname %>
      Add Note: <%= form.text_area(:content, cols: 70, rows: 1) %>
      <%= form.submit %>
<% end %>

app/views/comments/create.js.erb
$('#new-comment form').remove();
$('#new-comment a').show();
$('#comments').append("<%= j render '/shared/comment', comment: @comment %>")

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', [@opportunity, @comment] %> |
<%= link_to 'Back', opportunity_comments_path(@opportunity) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Comments for Opportunity: <%= @opportunity.customer_name %></h4>

<table class="border border-light">
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.content %></td>
        <td><%#= link_to 'Edit Comment', edit_opportunity_comment_path(@opportunity, comment) %>
          <%= link_to edit_opportunity_comment_path(@opportunity, comment) do %>
              <%= fa_icon "pencil-alt 1x" %>
          <% end %>
        </td>
        <td><%#= link_to 'Delete Comment', [@opportunity, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to [@opportunity, comment], method: :delete, data: {confirm: 'Are you sure?' } do %>
            <%= fa_icon "trash 1x" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_opportunity_comment_path(@opportunity) %>
<%= link_to 'Back to Opportunity', opportunity_path(@opportunity) %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back to Opportunity', opportunity_comments_path(@opportunity) %>

app/views/comments/new.js.erb
$('#new-comment a').hide().parent().append("<%= j render 'new_comment', comment: @comment %>")

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Opportunity Name:</strong>
  <%= @comment.opportunity.customer_name %>
</p>

<%= link_to 'Edit', edit_opportunity_comment_path(@opportunity, @comment) %> |
<%= link_to 'Back', opportunity_comments_path(@opportunity) %>