config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'pages/index'
  get 'pages/about'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :account_executives
  resources :salespeople
  resources :salepeople
  resources :engineers
  resources :sales_stages
  resources :products
  resources :opportunities do
    resources :comments
    resources :support_opportunities
    #get 'search', to: 'opportunities#search', as: 'search', on: :collection
    get 'search', to: 'opportunities#search', on: :collection
  end
  get 'my-top-opps', to: 'opportunities#tracking', as: 'tracking'
  get 'ac-opps', to: 'support_opportunities#acopps', as: 'acopps'
  resources :support_opportunities do
    resources :opportunities
    resources :apple_cares
  end
  resources :apple_cares

  root to: "opportunities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/support_opportunity.rb
class SupportOpportunity < ApplicationRecord
	belongs_to :apple_care
	belongs_to :opportunity

	#scope :my_carrier, -> { where carrier: current_user.carrier } 

	
end

app/controllers/support_opportunities_controller.rb
class SupportOpportunitiesController < ApplicationController
  before_action :get_opportunity, except: [:index, :acopps]
  before_action :set_support_opportunity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @page_title = "All AppleCare Opportunities"
    @support_opportunities = SupportOpportunity.all
    
  end

  def acopps
    carrier = current_user.carrier
    @page_title = "#{carrier.upcase} Team AppleCare Opportunities"
    @support_opportunities = SupportOpportunity.joins(:opportunity).where(opportunities: {carrier: carrier })
  
    #else
    #  @articles = SupportOpportunity.all
    #end
  end

  def show
  end

  def new
    #@support_opportunity = SupportOpportunity.new
    @support_opportunity = @opportunity.support_opportunities.build
  end

  def edit
  end

  def create
    @support_opportunity = @opportunity.support_opportunities.build(support_opportunity_params)

    respond_to do |format|
      if @support_opportunity.save
        format.html { redirect_to opportunity_path(@opportunity), notice: 'Support Opportunity was successfully created.' }
        #format.json { render :show, status: :created, location: @support_opportunity }
      else
        format.html { render :new }
        format.json { render json: @support_opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @support_opportunity.update(support_opportunity_params)
        format.html { redirect_to opportunity_support_opportunity_path(@opportunity), notice: 'Support Opportunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @support_opportunity }
      else
        format.html { render :edit }
        format.json { render json: @support_opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @support_opportunity.destroy
    respond_to do |format|
      format.html { redirect_to opportunity_path(@opportunity), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_opportunity
      @opportunity = Opportunity.find(params[:opportunity_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_support_opportunity
      @support_opportunity = SupportOpportunity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def support_opportunity_params
      params.require(:support_opportunity).permit(:opportunity_id, :apple_care_id, :fiscal_year, :fiscal_quarter, apple_cares_attributes: [ :id, :product, :_destroy ], support_opportunities_attributes: [ :id, :_destroy ])
    end

end

app/views/support_opportunities/_form.html.erb
<!-- /support_opportunities/_form.html.erb -->
<div class="col-md-12 col-sm-12">
  <%= form_with(model: [@opportunity, support_opportunity], local: true) do |form| %>
    <% if support_opportunity.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(support_opportunity.errors.count, "error") %> prohibited this support_opportunity from being saved:</h2>

        <ul>
        <% support_opportunity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-md-6 col-sm-12">


          <div class="form-group">
            <%= form.label :product %>
            <%= form.collection_select(:apple_care_id, AppleCare.all.applecare_by_id, :id, :product,
                          {
                            selected: support_opportunity.apple_care_id,
                            include_blank: true
                          },
                          class: 'form-control'
                        )
            %>
          </div>
<!-- NEED TO FIX THIS SO IT SHOWS THE CURRENT VALUE OF fiscal_quarter -->
          <div class="form-group">
            <%= form.label :fiscal_quarter %>
            <%= form.select(:fiscal_quarter, options_for_select(["Q1", "Q2", "Q3", "Q4"]), { :selected => :fiscal_quarter || nil }, { :class => 'form-control' } ) %>
          </div>

          <div class="form-group">
            <%= form.label :fiscal_year %>
    
            <%= form.date_select :fiscal_year, {start_year: Time.now.year, end_year: Time.now.year + 4, discard_month: true}, { :class => 'form-control' } %>
          </div>
    </div>

      <div class="col-md-12 col-sm-12">
        <%= form.submit class: "btn btn-primary btn-block mt-1 mb-4" %>
      </div>  
  <% end %>
</div>
<!-- </div> -->

app/views/support_opportunities/acopps.html.erb
<div class="container-fluid">
    <div class="row">
    <div class="col-lg-8">
        <h1><%= @page_title %></h1>
    </div>
    <div class="col-lg-4">
      <%= link_to 'New Opportunity', new_opportunity_path, class: "btn btn-primary mb-4 btn-sm float-right" %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
        <div class="text-center mb-3"><%#= paginate @opportunities %></div>
        <table class="table table-striped table-hover ">
          <!-- <col width="200"> -->
          <thead class="thead-dark">
            <tr>
              <th width="200">Customer Name</th>
              <th>AppleCare Product</th>
              <th>Anticipated Close Date</th>
              <th>Read Opportunity</th>
            </tr>
          </thead>


          <tbody>
          <% if @support_opportunities.empty? %>
              <div class="smc-alert"> There are no records matching your search criteria </div>
          <% else %>
            <% @support_opportunities.each do |support_opportunity| %>
              <tr>
                <td><%= support_opportunity.opportunity.customer_name %></td>
                <td><%= support_opportunity.apple_care.product %></td>
                <td><%= support_opportunity.fiscal_quarter %>-<%= support_opportunity.fiscal_year.strftime("%Y") %></td>
                <td>
                  <%= link_to opportunity_path(support_opportunity.opportunity_id) do %>
                    <%= fa_icon "glasses 1x" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
        <div class="text-center mt-3"><%#= paginate @opportunities %></div>  
    </div>
  </div>
</div>

app/views/support_opportunities/edit.html.erb
	<!-- /support_opportunities/show.html.erb  -->

	<div class="row">
        <div class="col-sm-12 col-md-12">
			<%= link_to 'Back to Pipeline List', support_opportunities_path, class: "btn btn-primary btn-lg mt-2 mb-5 float-right" %>
		</div>
		<div class="col-sm-12 col-md-12">
			<h2>Editing Support Opportunity for <%= @support_opportunity.opportunity.customer_name %></h2>
		</div>
		<%= render 'form', support_opportunity: @support_opportunity %>	
    </div>

app/views/support_opportunities/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
        <div class="text-center mb-3"><%#= paginate @opportunities %></div>
        <table class="table table-striped table-hover ">
          <!-- <col width="200"> -->
          <thead class="thead-dark">
            <tr>
              <th width="200">Customer Name</th>
              <th>AppleCare Product</th>
              <th>Anticipated Close Date</th>
              <th>Read Opportunity</th>
            </tr>
          </thead>


          <tbody>
            <% @support_opportunities.each do |support_opportunity| %>
              <tr>
                <td><%= support_opportunity.opportunity.customer_name %></td>
                <td><%= support_opportunity.apple_care.product %></td>
                <td><%= support_opportunity.fiscal_quarter %>-<%= support_opportunity.fiscal_year.strftime("%Y") %></td>
                <td>
                  <%= link_to opportunity_path(support_opportunity.opportunity_id) do %>
                    <%= fa_icon "glasses 1x" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="text-center mt-3"><%#= paginate @opportunities %></div>  
    </div>
  </div>
</div>

app/views/support_opportunities/new.html.erb
	<div class="row">
        <%#= render 'top_form_nav' %>
		<div class="col-sm-12 col-md-12">
			<h2>New AppleCare Opportunity</h2>
		</div>
		<%#= render 'form', support_opportunity: @support_opportunity %>
		<%= render 'form', support_opportunity: @support_opportunity %>
	</div>

app/views/support_opportunities/show.html.erb
<p>
  <strong>Customer Name:</strong>
  <%= @support_opportunity.opportunity.customer_name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @support_opportunity.apple_care.product %>
</p>

<p>
  <strong>Anticipated Close Date:</strong>
  <%= @support_opportunity.fiscal_quarter %> <%= @support_opportunity.fiscal_year.strftime("%Y") %>
</p>

<%= link_to 'Edit', edit_support_opportunity_path(@support_opportunity) %> | 

<%= link_to 'Back', opportunity_path(@support_opportunity) %>