config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'pages/index'
  get 'pages/about'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :account_executives
  resources :salespeople
  resources :salepeople
  resources :engineers
  resources :sales_stages
  resources :products
  resources :opportunities do
    resources :comments
    resources :support_opportunities
    #get 'search', to: 'opportunities#search', as: 'search', on: :collection
    get 'search', to: 'opportunities#search', on: :collection
  end
  get 'my-top-opps', to: 'opportunities#tracking', as: 'tracking'
  get 'ac-opps', to: 'support_opportunities#acopps', as: 'acopps'
  resources :support_opportunities do
    resources :opportunities
    resources :apple_cares
  end
  resources :apple_cares

  root to: "opportunities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/opportunity.rb
class Opportunity < ApplicationRecord
	include Filterable
	belongs_to :product
	accepts_nested_attributes_for :product

	enum stage: { not_specified: 0, prospect_qualify: 1, propose: 2, negotiate: 3, shipped: 4, lost: 5 }

	belongs_to :account_exec_user
	belongs_to :sys_engineer_user
	has_many :comments, inverse_of: :opportunity
	accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
	
    has_many :support_opportunities
	has_many :apple_cares, through: :support_opportunities
    accepts_nested_attributes_for :apple_cares

    scope :filter_by_stage, -> (stage) { where stage: stage }
    scope :filter_by_carrier, -> (carrier) { where carrier: carrier }
    scope :filter_by_quantity_gte, -> (quantity) { where('quantity >= ?', quantity) }
    scope :filter_by_quantity_lte, -> (quantity) { where('quantity <= ?', quantity) }
    scope :filter_by_user_with_name_like, -> (name) { where("account_exec_user_id LIKE ? or sys_engineer_user_id LIKE ?", name, name ) }
    scope :filter_by_created_before, -> (created_at) { where('created_at < ?', created_at.to_date ) }    
    scope :filter_by_created_after, -> (created_at) { where('created_at > ?', created_at.to_date ) }
    scope :filter_by_updated_before, -> (updated_at) { where('updated_at < ?', updated_at.to_date ) }    
    scope :filter_by_updated_after, -> (updated_at) { where('updated_at > ?', updated_at.to_date ) }

    scope :count_all_shipped, -> { Opportunity.all.where( stage: "shipped").size }
    scope :count_all_lost, -> { Opportunity.all.where( stage: "lost").size }
    scope :count_all_negotiate, -> { Opportunity.all.where( stage: "negotiate").size }
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  before_action :set_opportunity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /opportunities
  # GET /opportunities.json
  def index 
    if current_user.role == "admin" || current_user.role == "manager"
      @page_title = "Manager View of Pipeline"
      @opportunities = opportunity.filter(params.slice(:stage, :carrier, :quantity_gte, :quantity_lte, :fullname, :user_with_name_like, :created_before, :created_after, :created_at, :updated_before, :updated_after, :updated_at )).page params[:page]
      @total_opps = Opportunity.all
    else
      @page_title = "Team Opportunity Pipeline"
      @my_opportunities = Opportunity.where(carrier: current_user.carrier).order(updated_at: :desc).page params[:page]
      @opportunities = @my_opportunities.filter(params.slice(:stage, :carrier, :quantity_gte, :quantity_lte, :fullname, :user_with_name_like, :created_before, :created_after, :created_at, :updated_before, :updated_after, :updated_at )).page params[:page]
      @total_opps = @my_opportunities
    end
  end

  def search
    @page_title = "Custom Search"
    if params[:search]
      search_term = params[:search].downcase.gsub(/\s+/, "")
      #@opportunities = Opportunity.all.page params[:page]
      @opportunities = Opportunity.all.select { |opportunity|
              opportunity.customer_name.downcase.include?(search_term) || 
              opportunity.product.model.downcase.include?(search_term) || 
              opportunity.carrier.include?(search_term) || 
              opportunity.account_exec_user.fullname.downcase.include?(search_term) || 
              opportunity.sys_engineer_user.fullname.downcase.include?(search_term) ||
              opportunity.use_case.downcase.include?(search_term) ||
              opportunity.stage == search_term
              #opportunity.industry.downcase.include?(search_term)
            }
    else
      @opportunities = []
    end

  end

  def tracking
    @page_title = "My Top Opps"
    @top_opportunities = Opportunity.where(carrier: current_user.carrier, tracking: :true).order(updated_at: :desc).page params[:page]
  end

  # GET /opportunities/1
  # GET /opportunities/1.json
  def show
  end

  # GET /opportunities/new
  def new
    @opportunity = Opportunity.new
    3.times { @opportunity.comments.build }
  end

  # GET /opportunities/1/edit
  def edit
  end

  # POST /opportunities
  # POST /opportunities.json
  def create
    @opportunity = Opportunity.new(opportunity_params)

    respond_to do |format|
      if @opportunity.save
        format.html { redirect_to opportunities_path, notice: 'Opportunity was successfully created.' }
        format.json { render :show, status: :created, location: @opportunity }
      else
        format.html { render :new }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opportunities/1
  # PATCH/PUT /opportunities/1.json
  def update
    respond_to do |format|
      if @opportunity.update(opportunity_params)
        format.html { redirect_to opportunities_path, notice: 'Opportunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @opportunity }
      else
        format.html { render :edit }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opportunities/1
  # DELETE /opportunities/1.json
  def destroy
    @opportunity.destroy
    respond_to do |format|
      format.html { redirect_to opportunities_url, notice: 'Opportunity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opportunity
      @opportunity = Opportunity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def opportunity_params
      params.require(:opportunity).permit(:customer_name, :stage, :quantity, :quantity_gte, :quantity_lte, :created_before, :created_after, :created_at, :user_with_name_like, :fullname, :use_case, 
                                          :sales_stage_id, :product_id, :model, :account_exec_user_id, 
                                          :sys_engineer_user_id, :carrier, :tracking,
                                          comments_attributes: [ :id, :author, :content, :_destroy ])
    end
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/opportunities/_comment_fields.html.erb
   
<div class='nested-fields'>
	<%= f.hidden_field :author, value: current_user.fullname %>
    <%= f.text_area :content %>
    <%= link_to_remove_association( "remove comment", f, {}) %>
</div>
    

app/views/opportunities/edit.html.erb
<!-- <div class="container"> -->
	<div class="row">
		<div class="col-sm-12 col-md-12">
			<h2>Editing Opportunity for <%= @opportunity.customer_name %></h2>
		</div>
		<%= render 'form', opportunity: @opportunity %>	
    </div>
<!-- </div> -->

app/views/opportunities/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
        <h1><%= @page_title %></h1>
    </div>
    <div class="col-lg-4">
      <%= link_to 'New Opportunity', new_opportunity_path, class: "btn btn-primary mb-4 btn-sm float-right" %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 bg-light clearfix p-4 form-group rounded-lg">
      <div class="row">
        <div class="col-lg-4">
          <div class="card border-success">
            <div class="card-body text-center text-success">
              <h2>Shipped: <%= @total_opps.count_all_shipped %></h2>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card border-warning">
            <div class="card-body text-center text-warning">
              <h2>Negotiate: <%= @total_opps.count_all_negotiate %></h2>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card  border-danger">
            <div class="card-body text-center text-danger">
              <h2>Lost: <%= @total_opps.count_all_lost %></h2>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 bg-light clearfix p-4 form-group rounded-lg">
      <!-- Row 1 Start -->
      <div class="row">
        <div class="col-lg-4 text-right mb-4">
          <!-- Column -->
          <dir class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >AE Owner</span> 
              <%= select_tag :user_with_name_like, options_from_collection_for_select(AccountExecUser.all, :id, :lastname, params[:account_exec_user_id]), include_blank: true, class: "form-control form-control-sm" %>
              <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </dir>
          <div class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >SE Owner</span> 
              <%= select_tag :user_with_name_like, options_from_collection_for_select(SysEngineerUser.all, :id, :lastname, params[:sys_engineer_user]), include_blank: true, class: "form-control form-control-sm" %>
              <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
        </div>
        <!-- Column -->
        <div class="col-lg-4 text-right mb-4">
          <div class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Units > Than</span> <%= search_field_tag 'quantity_gte', '', class: 'form-control form-control-sm mr-sm-1', disabled: false, :size=>"5" %>
              <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
          <div class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Units < Than</span> <%= search_field_tag 'quantity_lte', '', class: 'form-control form-control-sm mr-sm-1', disabled: false, :size=>"5" %>
              <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
        </div>
        <!-- Column -->
        <div class="col-lg-4 text-right mb-4">
          <div class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Sales Stage</span> <%= select_tag "stage", options_for_select([ ["All Stages", ""], ["Prospect/Qualify", "prospect_qualify"], ["Propose", "propose"], ["Negotiate", "negotiate"], ["Shipped", "shipped"], ["Lost", "lost"]]), { class: "form-control form-control-sm" } %> 
              <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
        <% if current_user.role == "admin" || current_user.role == "manager" %>
          <div class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Carrier</span> <%= select_tag "carrier", options_for_select([ ["All Carriers", ""], ["Verizon", "verizon"], ["AT&T", "att"], ["T-Mobile", "t-mobile"]]), { class: "form-control form-control-sm" } %> 
              <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
        <% end %>
        </div>
      </div>
      <!-- Row 1 End -->
      <!-- Row 2 Start -->
      <div class="row">
        <!-- Column -->
        <div class="col-lg-4 text-right mb-4">
          <div id="datepicker" class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Created Before</span> <%= search_field_tag 'created_before', '', class: 'datepicker form-control form-control-sm mr-sm-1', disabled: false, :size=>"10" %>
            <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
          <div id="datepicker" class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Created After</span> <%= search_field_tag 'created_after', '', class: 'datepicker form-control form-control-sm mr-sm-1', disabled: false, :size=>"10" %>
            <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
        </div>
        <!-- Column -->
        <div class="col-lg-4 text-right mb-4">
          <div id="datepicker" class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Updated Before</span> <%= search_field_tag 'updated_before', '', class: 'datepicker form-control form-control-sm mr-sm-1', disabled: false, :size=>"10" %>
            <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>
          </div>
          <div id="datepicker" class="mb-2 float-right">
            <%= form_tag(opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <span class="mr-2 text-dark" >Updated After</span> <%= search_field_tag 'updated_after', '', class: 'datepicker form-control form-control-sm mr-sm-1', disabled: false, :size=>"10" %>
            <%= submit_tag 'Search', class: "btn btn-outline-success btn-sm my-2 my-sm-0 ml-2" %>
            <% end %>

          </div>
        </div>
      </div>
      <!-- Row 2 End -->
      <!-- Row 3 Start -->
      <div class="row">
        <div class="col-lg-12 text-center mb-4">
            <%= link_to "Reset Form", opportunities_path, class: "btn btn-success btn-sm my-2 my-sm-0 ml-2" %>
        </div>  
      </div>
      <!-- Row 3 End -->
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
        <div class="text-center mb-3"><%= paginate @opportunities %></div>
        <table class="table table-striped table-hover ">
          <!-- <col width="200"> -->
          <thead class="thead-dark">
            <tr>
              <th width="20"></th>
              <th width="200">Customer Name</th>
              <th>Stage</th>
              <th>Quantity</th>
              <th>Product</th>
              <th>Use Case</th>
              <th>Apple AE</th>
              <th>Apple SE</th>
              <th>Carrier</th>
              <th>Last Update</th>
              <th>Created On</th>
              <th colspan="3"></th>
            </tr>
          </thead>


          <tbody>
          <% if @opportunities.empty? %>
              <div class="smc-alert"> There are no records matching your search criteria </div>
          <% else %>
            <% @opportunities.each do |opportunity| %>
              <tr>
                <td class="<%= opportunity.stage %>" width="10"></td>
                <td><%= opportunity.customer_name %></td>
                <td><%= opportunity.stage %></td>
                <td><%= opportunity.quantity %></td>
                <td><%= opportunity.product.model %></td>
                <td><%= truncate(opportunity.use_case, length: 80 ) %></td>
                <td><%= opportunity.account_exec_user.firstname %> <%= opportunity.account_exec_user.lastname %></td>
                <td><%= opportunity.sys_engineer_user.firstname %> <%= opportunity.sys_engineer_user.lastname %></td>
                <td><%= opportunity.carrier %></td>
                <td><%= time_ago_in_words(opportunity.updated_at) %> ago</td>
                <td><%= opportunity.created_at.strftime("%m/%d/%Y") %></td>
                <td>
                  <%= link_to opportunity do %>
                      <%= fa_icon "glasses 1x" %>
                  <% end %>
                </td>

                <td>
                  <%= link_to edit_opportunity_path(opportunity) do %>
                      <%= fa_icon "pencil-alt 1x" %>
                  <% end %>
                </td>
                <td>
                  <% if current_user.role == "admin" || current_user.role == "manager" %>
                    <%= link_to opportunity, method: :delete, data: {confirm: 'Are you sure?' } do %>
                      <%= fa_icon "trash 1x" %>
                    <% end %>
                  <% end %>
                </td>  
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
        <div class="text-center mt-3"><%= paginate @opportunities %></div>  
    </div>
  </div>
</div>

app/views/opportunities/new.html.erb
<!-- <div class="container"> -->
	<div class="row">
        <%#= render 'top_form_nav' %>
		<div class="col-sm-12 col-md-12">
			<h2>New Opportunity</h2>
		</div>
		<%= render 'form', opportunity: @opportunity %>
	</div>
<!-- </div> -->

app/views/opportunities/search.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
        <h1><%= @page_title %></h1>
    </div>
    <div class="col-lg-4">
      <%= link_to 'New Opportunity', new_opportunity_path, class: "btn btn-primary mb-4 btn-sm float-right" %>
    </div>
  </div>
  <!-- Search Row -->
  <div class="row">
    <div class="col-lg-12 bg-light clearfix p-4 form-group rounded-lg">
      <div class="row">
        <div class="col-lg-12 text-right mb-4">
          <div class="search">
            <%= form_tag(search_opportunities_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
                Search By Customer Name, AE, SE, Keyword, Use Case, sales stage, or Product <%= text_field_tag :search, params[:search], class: "form-inline my-2 my-lg-0 ml-2" %>
              <%= submit_tag 'Search 🔍', name: nil, class: "btn btn-outline-success btn-sm form-inline my-2 my-sm-0 ml-2" %>
            <% end %>
          </div> 
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
        <div class="text-center mb-3"><%#= paginate @opportunities unless @opportunities.empty? %></div>
        <table class="table table-striped table-hover ">
          <!-- <col width="200"> -->
          <thead class="thead-dark">
            <tr>
              <th width="20"></th>
              <th width="200">Customer Name</th>
              <th>Stage</th>
              <th>Quantity</th>
              <th>Product</th>
              <th>Use Case</th>
              <th>Apple AE</th>
              <th>Apple SE</th>
              <th>Carrier</th>
              <th>Last Update</th>
              <th>Created On</th>
              <th colspan="3"></th>
            </tr>
          </thead>


          <tbody>
          <% if @opportunities.empty? %>
              <div class="smc-alert"> There are no records matching your search criteria </div>
          <% else %>
            <% @opportunities.each do |opportunity| %>
              <tr>
                <td class="<%= opportunity.stage %>" width="10"></td>
                <td><%= opportunity.customer_name %></td>
                <td><%= opportunity.stage %></td>
                <td><%= opportunity.quantity %></td>
                <td><%= opportunity.product.model %></td>
                <td><%= truncate(opportunity.use_case, length: 80 ) %></td>
                <td><%= opportunity.account_exec_user.firstname %> <%= opportunity.account_exec_user.lastname %></td>
                <td><%= opportunity.sys_engineer_user.firstname %> <%= opportunity.sys_engineer_user.lastname %></td>
                <td><%= opportunity.carrier %></td>
                <td><%= time_ago_in_words(opportunity.updated_at) %> ago</td>
                <td><%= opportunity.created_at.strftime("%m/%d/%Y") %></td>
                <td>
                  <%= link_to opportunity do %>
                      <%= fa_icon "glasses 1x" %>
                  <% end %>
                </td>

                <td>
                  <%= link_to edit_opportunity_path(opportunity) do %>
                      <%= fa_icon "pencil-alt 1x" %>
                  <% end %>
                </td>
                <td>
                  <% if current_user.role == "admin" || current_user.role == "manager" %>
                    <%= link_to opportunity, method: :delete, data: {confirm: 'Are you sure?' } do %>
                      <%= fa_icon "trash 1x" %>
                    <% end %>
                  <% end %>
                </td>  
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
         
    </div>
  </div>
</div>

app/views/opportunities/show.html.erb
<div class="row mb-2">
  <div class="col-sm-12 col-md-12">
    <%= link_to 'Back to Pipeline List', opportunities_path, class: "btn btn-primary btn-lg mt-2 mb-5 float-right" %>
  </div>
  <div class="col-md-12"><h2>Opportunity Details for: <%= @opportunity.customer_name %></h2></div>
</div>

<div class="row">
  <!-- Left side column -->
  <!-- OPPORTUNITY DETAILS SECTION -->
  <div class="col-md-6 float-left">
    <table class="table table-sm table-responsive-sm border border-dark bg-light">
      <thead class="thead-dark">
        <th>Details</th>
        <th></th>
      </thead>
      <tbody>
          <tr>
            <td><strong>Stage</strong></td>
            <td><%= @opportunity.stage %></td>
          </tr>
          <tr>
            <td><strong>Quantity</strong></td>
            <td><%= @opportunity.quantity %></td>
          </tr>
          <tr>
            <td><strong>Product</strong></td>
            <td><%= @opportunity.product.model %></td>
          </tr>
          <tr>
            <td><strong>Use Case</strong></td>
            <td><%= @opportunity.use_case %></td>
          </tr>
          <tr>
            <td><strong>Tracking?</strong></td>
            <td><%= @opportunity.tracking %></td>
          </tr>
      </tbody>
    </table>
    <%= link_to 'Edit Opportunity', edit_opportunity_path(@opportunity), class: "btn btn-primary btn-lg mt-2 mb-4 btn-block" %>
  </div>
  <!-- Left side column -->
  <!-- APPLECARE OPPORTUNITIES SECTION -->
  <div class="col-md-6 float-left">
    <table class="table table-sm table-responsive-sm border border-dark bg-light">
      <thead class="thead-dark">
        <th><strong>AppleCare Product</strong></th>
        <th><strong>Anticipated Close</strong></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
        <% @opportunity.support_opportunities.each do |support_opportunity| %>
          <tr>
            <td><%= support_opportunity.apple_care.product %></td>
            <td><%= support_opportunity.fiscal_quarter %> <%= support_opportunity.fiscal_year.strftime("%Y") %>
            </td>
            <td>
              <%= link_to opportunity_support_opportunity_path(@opportunity, support_opportunity) do %>
                  <%= fa_icon "glasses 1x" %>
              <% end %>
            </td>
            <td>
              <%= link_to edit_opportunity_support_opportunity_path(@opportunity, support_opportunity) do %>
                  <%= fa_icon "pencil-alt 1x" %>
              <% end %>
            </td>
            <td>
              <%# if current_user.role == "admin" || current_user.role == "manager" %>
                <%= link_to [@opportunity, support_opportunity], method: :delete, data: {confirm: 'Are you sure?' } do %>
                  <%= fa_icon "trash 1x" %>
                <% end %>
              <%# end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Add AppleCare Product', new_opportunity_support_opportunity_path(@opportunity) %>
  </div>
<!-- Right side column -->
<!-- COMMENTS SECTION -->
  <div class="col-md-12 float-right">
    <table class="table table-sm table-responsive-sm border border-dark bg-light">
      <thead class="thead-dark">
        <tr>
          <th>Author</th>
          <th>Notes</th>
          <th>Created On</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="comments">
        <%= render partial: '/shared/comment', collection: @opportunity.comments %>
      </tbody>
    </table>
    <div id="new-comment">
      <%= link_to 'Add Notes', new_opportunity_comment_path(@opportunity), remote: true, class: "btn btn-primary btn-sm mt-2 mb-4" %>
    </div>

  </div>
</div>
<div class="row">

</div>

app/views/opportunities/tracking.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
        <h1><%= @page_title %></h1>
    </div>
    <div class="col-lg-4">
      <%= link_to 'New Opportunity', new_opportunity_path, class: "btn btn-primary mb-4 btn-sm float-right" %>
    </div>
  </div>
    <div class="col-lg-12">
        <div class="text-center mb-3"><%= paginate @top_opportunities %></div>
        <table class="table table-striped table-hover ">
          <!-- <col width="200"> -->
          <thead class="thead-dark">
            <tr>
              <th width="20"></th>
              <th width="200">Customer Name</th>
              <th>Stage</th>
              <th>Quantity</th>
              <th>Product</th>
              <th>Use Case</th>
              <th>Apple AE</th>
              <th>Apple SE</th>
              <th>Carrier</th>
              <th>Last Update</th>
              <th>Created On</th>
              <th colspan="3"></th>
            </tr>
          </thead>


          <tbody>
          <% if @top_opportunities.empty? %>
              <div class="smc-alert"> There are no records matching your search criteria </div>
          <% else %>
            <% @top_opportunities.each do |opportunity| %>
              <tr>
                <td class="<%= opportunity.stage %>" width="10"></td>
                <td><%= opportunity.customer_name %></td>
                <td><%= opportunity.stage %></td>
                <td><%= opportunity.quantity %></td>
                <td><%= opportunity.product.model %></td>
                <td><%= truncate(opportunity.use_case, length: 80 ) %></td>
                <td><%= opportunity.account_exec_user.firstname %> <%= opportunity.account_exec_user.lastname %></td>
                <td><%= opportunity.sys_engineer_user.firstname %> <%= opportunity.sys_engineer_user.lastname %></td>
                <td><%= opportunity.carrier %></td>
                <td><%= time_ago_in_words(opportunity.updated_at) %> ago</td>
                <td><%= opportunity.created_at.strftime("%m/%d/%Y") %></td>
                <td>
                  <%= link_to opportunity do %>
                      <%= fa_icon "glasses 1x" %>
                  <% end %>
                </td>

                <td>
                  <%= link_to edit_opportunity_path(opportunity) do %>
                      <%= fa_icon "pencil-alt 1x" %>
                  <% end %>
                </td>
                <td>
                  <% if current_user.role == "admin" || current_user.role == "manager" %>
                    <%= link_to opportunity, method: :delete, data: {confirm: 'Are you sure?' } do %>
                      <%= fa_icon "trash 1x" %>
                    <% end %>
                  <% end %>
                </td>  
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
        <div class="text-center mt-3"><%= paginate @top_opportunities %></div>  
    </div>
  </div>
</div>